### ISSUE TITLE
 make the function private

### ISSUE THREAD

**Issue by mnaveedb** [lmengnr/bhootd#31]
In file cpustat.hpp

void getHostname(std::string &hostname) 
I would rather delare it like 
std::string  getHostname()
also making the function private member.

**Comment by lmengnr** [comment]
> In file cpustat.hpp
> 
> void getHostname(std::string &hostname)
> I would rather delare it like
> std::string getHostname()
> also making the function private member.

Thanks again. This function wasn't even in use, so I got rid of it.
